# Generated by Django 4.2.1 on 2023-05-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0002_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='none@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
